### ISSUE TITLE
Queries never return results and continue spinning

### ISSUE THREAD

**Issue by jonyee** [notebookPowerTools/vscode-kusto#58]
When I run a query, the query spinner just keeps spinning and the status icon below my query shows pending.

I get autocomplete in the code cell so auth appears to be fine, but I don't know why I'm not getting results.

Any steps I can take to debug?  Even just a simple `print "hello world"` fails like this.

**Comment by anshulahuja98** [comment]
+1, seeing the same issue.

**Comment by anshulahuja98** [comment]
Extension version 0.3.8 - this is the latest available from marketplace. I see that 0.4.3 is your latest on the repo.
VS Code version: January 2023 (version 1.75)
Dev tools errors: 
![image](https://user-images.githubusercontent.com/36476228/224932484-4026d6cb-83dd-4732-800b-63405f71d955.png)

**Comment by anshulahuja98** [comment]
Force installing 0.4.3 is not working
![image](https://user-images.githubusercontent.com/36476228/224933731-4bcea6fd-ba45-4e58-a3af-b223761d3677.png)

**Comment by anshulahuja98** [comment]
I see in the package config that 1.76 + is supported.
Updating VSCode and trying now

**Comment by anshulahuja98** [comment]
It works now!
Thank you!
